
project_id = "qpswgrmvepttnfetpopk"

[api]
enabled = true
port = 54330
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54325

[realtime]
enabled = true

[functions]
[functions.podio-user-auth]
verify_jwt = false

[functions.podio-oauth-callback]
verify_jwt = false

[functions.podio-token-refresh]
verify_jwt = false

[functions.podio-proxy]
verify_jwt = false

[functions.podio-get-auth-url]
verify_jwt = false
