project_id = "qpswgrmvepttnfetpopk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[functions]
[functions.health-check]
verify_jwt = false