project_id = "qpswgrmvepttnfetpopk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[functions]
[functions.health-check]
verify_jwt = false

[functions.podio-user-auth]
verify_jwt = false

[functions.podio-oauth-callback]
verify_jwt = false

[functions.podio-proxy]
verify_jwt = false

[functions.podio-oauth-url]
verify_jwt = false

[functions.podio-authenticate]
verify_jwt = false