project_id = "qpswgrmvepttnfetpopk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[functions]
[functions.health-check]
verify_jwt = false

[functions.podio-oauth-url]
verify_jwt = false

[functions.podio-oauth-callback]
verify_jwt = false

[functions.podio-api-proxy]
verify_jwt = true

[functions.test-env]
verify_jwt = false
